ALTER TABLE "poste" DISABLE TRIGGER ALL;
ALTER TABLE "souscategorie" DISABLE TRIGGER ALL;
ALTER TABLE "categorie" DISABLE TRIGGER ALL;
ALTER TABLE "exercice" DISABLE TRIGGER ALL;
ALTER TABLE "ecriture" DISABLE TRIGGER ALL;
ALTER TABLE "compte" DISABLE TRIGGER ALL;

TRUNCATE TABLE "poste" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "souscategorie" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "categorie" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "exercice" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "ecriture" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "compte" RESTART IDENTITY CASCADE;

ALTER TABLE "poste" ENABLE TRIGGER ALL;
ALTER TABLE "souscategorie" ENABLE TRIGGER ALL;
ALTER TABLE "categorie" ENABLE TRIGGER ALL;
ALTER TABLE "exercice" ENABLE TRIGGER ALL;
ALTER TABLE "ecriture" ENABLE TRIGGER ALL;
ALTER TABLE "compte" ENABLE TRIGGER ALL;
